import uniqid from 'uniqid';

// TODO: Change brand from string to brand ID once database is set up
const productData = [
    {
        id: uniqid(),
        name: 'Nupste Puffer Jacket',
        type: 'outerwear',
        brand: 'The North Face',
        price: 220,
        imageURL: '/products/tnf-nupste.webp',
        description: 'Very nice puffer jacket.',
        category: 'M',
        onSale: false,
    },
    {
        id: uniqid(),
        name: 'Script Logo Cap',
        type: 'headwear',
        brand: 'Kith',
        price: 60,
        imageURL: '/products/kith-scriptlogo.webp',
        description: 'Japanese baseball player type beat. Very nice look.',
        category: 'U',
        onSale: true,
    },
    {
        id: uniqid(),
        name: 'Anti-Expo Tee',
        type: 'shirt',
        brand: 'John Elliot',
        price: 98,
        imageURL: '/products/johnelliot-antiexpo.webp',
        description: 'Very nice green tee shirt. Made by John Elliot himself.',
        category: 'M',
        onSale: false,
    },
    {
        id: uniqid(),
        name: '501 Jeans',
        type: 'pants',
        brand: 'Levis',
        price: 80,
        imageURL: '/products/levis-501.webp',
        description: 'Classic jeans since the 1800s. Very nice.',
        category: 'M',
        onSale: false,
    },
    {
        id: uniqid(),
        name: 'Air Force 1',
        type: 'shoes',
        brand: 'Nike',
        price: 155,
        imageURL: '/products/nike-af1.webp',
        description: 'Be careful around people who wear these. Black air force energy is real.',
        category: 'M',
        onSale: true,
    },
    {
        id: uniqid(),
        name: 'Sire Jeans',
        type: 'pants',
        brand: 'Diesel',
        price: 250,
        imageURL: '/products/diesel-sire.webp',
        description: 'So slay. Very nice. Put these on if you like jeans.',
        category: 'W',
        onSale: false,
    },
    {
        id: uniqid(),
        name: 'Crop Knit Pullover',
        type: 'outerwear',
        brand: 'Champion',
        price: 100,
        imageURL: '/products/champion-crop.webp',
        description: 'Cropped to show your figure. Fit is very nice.',
        category: 'W',
        onSale: true,
    },
    {
        id: uniqid(),
        name: 'Tabi Boots',
        type: 'shoes',
        brand: 'Mason Margiela',
        price: 1250,
        imageURL: '/products/margiela-tabis.webp',
        description: 'Cropped to show your figure. Fit is very nice.',
        category: 'W',
        onSale: false,
    },
]

export default productData;